name: Frontend - Deploy to S3 & CloudFront

on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'public/**'
      - '.github/workflows/front.yml'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch: {}

env:
  AWS_REGION: us-east-1
  FRONT_BUCKET: frontend-nutrabiotics
  CLOUDFRONT_ID: E3RGYYU59V80HM

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Build & Upload Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: arn:aws:iam::534039229473:role/nutrabiotics-gha-role

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      # ATENCIÓN: No working-directory aquí
      - name: Install dependencies
        run: npm install

      # ATENCIÓN: No working-directory aquí
      - name: Build React app
        run: CI=false npm run build

      # Sync directo desde dist/
      - name: Sync to S3
        run: aws s3 sync dist/ s3://${{ env.FRONT_BUCKET }} --delete

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_ID }} \
            --paths "/*"
